export const REQUEST_AUTHENTICATE_USER = `REQUEST_AUTHENTICATE_USER`;
export const PROCESSING_AUTHENTICATE_USER = `PROCESSING_AUTHENTICATE_USER`;
export const AUTHENTICATING = `AUTHENTICATING`;
export const AUTHENTICATED = `AUTHENTICATED`;
export const NOT_AUTHENTICATED = `NOT_AUTHENTICATED`;

export const REQUEST_REGISTER_USER = `REQUEST_REGISTER_USER`;
export const PROCESSING_REGISTER_USER = `PROCESSING_REGISTER_USER`;
export const REGISTERING = `REGISTERING`;
export const REGISTER_SUCCESS = `REGISTER_SUCCESS`;
export const REGISTER_FAIL = `REGISTER_FAIL`;
